-- MySQL Script generated by MySQL Workbench
-- Fri Oct 14 15:19:40 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema clinicadental
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema clinicadental
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clinicadental` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `clinicadental` ;

-- -----------------------------------------------------
-- Table `clinicadental`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicadental`.`cargos` (
  `CodCargos` INT NOT NULL AUTO_INCREMENT,
  `Cargos` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`CodCargos`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `clinicadental`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicadental`.`categorias` (
  `CodCategoria` INT NOT NULL AUTO_INCREMENT,
  `Categoria` VARCHAR(45) NULL DEFAULT NULL,
  `Descripcion` VARCHAR(80) NULL DEFAULT NULL,
  PRIMARY KEY (`CodCategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `clinicadental`.`sucursales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicadental`.`sucursales` (
  `CodSucursal` INT NOT NULL AUTO_INCREMENT,
  `Sucursal` VARCHAR(45) NULL DEFAULT NULL,
  `Telefono` INT NULL DEFAULT NULL,
  `Direccion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`CodSucursal`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `clinicadental`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicadental`.`usuarios` (
  `CodUsuarios` INT NOT NULL AUTO_INCREMENT,
  `Usuarios` VARCHAR(45) NULL DEFAULT NULL,
  `Clave` VARCHAR(45) NULL DEFAULT NULL,
  `Rol` INT NULL DEFAULT NULL,
  PRIMARY KEY (`CodUsuarios`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `clinicadental`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicadental`.`personas` (
  `CodPersona` INT NOT NULL AUTO_INCREMENT,
  `CodUsuarios` INT NOT NULL,
  `CodCargos` INT NOT NULL,
  `CodSucursal` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NOT NULL,
  `FechaNac` DATE NOT NULL,
  `FechaRegistro` DATE NOT NULL,
  `DUI` INT NOT NULL,
  `Telefono` INT NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Estado` CHAR(1) NOT NULL,
  PRIMARY KEY (`CodPersona`),
  UNIQUE INDEX `DUI_UNIQUE` (`DUI` ASC) VISIBLE,
  UNIQUE INDEX `Telefono_UNIQUE` (`Telefono` ASC) VISIBLE,
  INDEX `CodUsuarios_idx` (`CodUsuarios` ASC) VISIBLE,
  INDEX `CodCargos_idx` (`CodCargos` ASC) VISIBLE,
  INDEX `CodSucursal_idx` (`CodSucursal` ASC) VISIBLE,
  CONSTRAINT `CodCargos`
    FOREIGN KEY (`CodCargos`)
    REFERENCES `clinicadental`.`cargos` (`CodCargos`),
  CONSTRAINT `CodSucursal`
    FOREIGN KEY (`CodSucursal`)
    REFERENCES `clinicadental`.`sucursales` (`CodSucursal`),
  CONSTRAINT `CodUsuarios`
    FOREIGN KEY (`CodUsuarios`)
    REFERENCES `clinicadental`.`usuarios` (`CodUsuarios`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `clinicadental`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicadental`.`factura` (
  `CodFactura` INT NOT NULL AUTO_INCREMENT,
  `NumFactura` INT NULL DEFAULT NULL,
  `Fecha` DATE NULL DEFAULT NULL,
  `Secretaria` INT NULL DEFAULT NULL,
  `Doctor` INT NULL DEFAULT NULL,
  `Cliente` INT NULL DEFAULT NULL,
  PRIMARY KEY (`CodFactura`),
  INDEX `fk_factura_secre` (`Secretaria` ASC) VISIBLE,
  INDEX `fk_factura_doctor` (`Doctor` ASC) VISIBLE,
  INDEX `fk_factura_cliente` (`Cliente` ASC) VISIBLE,
  CONSTRAINT `fk_factura_cliente`
    FOREIGN KEY (`Cliente`)
    REFERENCES `clinicadental`.`personas` (`CodPersona`),
  CONSTRAINT `fk_factura_doctor`
    FOREIGN KEY (`Doctor`)
    REFERENCES `clinicadental`.`personas` (`CodPersona`),
  CONSTRAINT `fk_factura_secre`
    FOREIGN KEY (`Secretaria`)
    REFERENCES `clinicadental`.`personas` (`CodPersona`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `clinicadental`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicadental`.`productos` (
  `CodProducto` INT NOT NULL AUTO_INCREMENT,
  `Producto` VARCHAR(45) NULL DEFAULT NULL,
  `CodCategoria` INT NULL DEFAULT NULL,
  PRIMARY KEY (`CodProducto`),
  INDEX `CodCategoria_idx` (`CodCategoria` ASC) VISIBLE,
  CONSTRAINT `CodCategoria`
    FOREIGN KEY (`CodCategoria`)
    REFERENCES `clinicadental`.`categorias` (`CodCategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `clinicadental`.`facturadetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicadental`.`facturadetalle` (
  `CodFactDeta` INT NOT NULL AUTO_INCREMENT,
  `NumFactura` INT NULL DEFAULT NULL,
  `CodProducto` INT NULL DEFAULT NULL,
  `Cantidad` INT NULL DEFAULT NULL,
  `Precio` INT NULL DEFAULT NULL,
  PRIMARY KEY (`CodFactDeta`),
  INDEX `NumFactura_idx` (`NumFactura` ASC) VISIBLE,
  INDEX `fk_factdeta_codprod` (`CodProducto` ASC) VISIBLE,
  CONSTRAINT `fk_factdeta_codprod`
    FOREIGN KEY (`CodProducto`)
    REFERENCES `clinicadental`.`productos` (`CodProducto`),
  CONSTRAINT `NumFactura`
    FOREIGN KEY (`NumFactura`)
    REFERENCES `clinicadental`.`factura` (`CodFactura`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `clinicadental`.`productosxpersona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicadental`.`productosxpersona` (
  `CodProdPers` INT NOT NULL AUTO_INCREMENT,
  `CodProducto` INT NULL DEFAULT NULL,
  `CodPersona` INT NULL DEFAULT NULL,
  PRIMARY KEY (`CodProdPers`),
  INDEX `CodProducto_idx` (`CodProducto` ASC) VISIBLE,
  INDEX `fk_prodxper_codpers` (`CodPersona` ASC) VISIBLE,
  CONSTRAINT `fk_prodxper_codpers`
    FOREIGN KEY (`CodPersona`)
    REFERENCES `clinicadental`.`personas` (`CodPersona`),
  CONSTRAINT `fk_prodxper_codprod`
    FOREIGN KEY (`CodProducto`)
    REFERENCES `clinicadental`.`productos` (`CodProducto`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `clinicadental`.`productoxsucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinicadental`.`productoxsucursal` (
  `CodProdSu` INT NOT NULL AUTO_INCREMENT,
  `CodProducto` INT NULL DEFAULT NULL,
  `CodSucursal` INT NULL DEFAULT NULL,
  `Cantidad` INT NULL DEFAULT NULL,
  `Estado` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`CodProdSu`),
  INDEX `CodProducto_idx` (`CodProducto` ASC) VISIBLE,
  INDEX `CodSucursal_idx` (`CodSucursal` ASC) VISIBLE,
  CONSTRAINT `CodProducto`
    FOREIGN KEY (`CodProducto`)
    REFERENCES `clinicadental`.`productos` (`CodProducto`),
  CONSTRAINT `fk_prodxsu_codsuc`
    FOREIGN KEY (`CodSucursal`)
    REFERENCES `clinicadental`.`sucursales` (`CodSucursal`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
