/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ujmdprc4.clinicadental;
import Properties.RegistroProperties;
import Clases.ComboCargos;
import Clases.Personas;
import Conexion.Conexion;
import static Properties.RegistroProperties.prop;
import java.io.IOException;
import static java.lang.Integer.parseInt;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author LENOVO
 */
public class InternalFrame_Personas extends javax.swing.JInternalFrame {
    Personas personas;
    RegistroProperties rp;
    
    int indiceCombo = 0;
    DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
    DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form InternalFrame_Personas
     */
    public InternalFrame_Personas() throws SQLException {
        try {
            rp = new RegistroProperties();
        } catch (IOException ex) {
            Logger.getLogger(Ingreso.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        CargarTexto();
        this.setSize(1366, 690);
        this.TablePersonas.setSize(500, 500);
        this.jdcFechaNac.setDateFormatString("yyyy-MM-dd");
        this.jdcFechaRegistro.setDateFormatString("yyyy-MM-dd");
        personas = new Personas();
        Conexion c = new Conexion();
        c.EstableceConexion();
        LlenarCombo();
        CargarDatos();
    }
    
    public void CargarDatos(){
        this.TablePersonas.setModel(personas.CargarPersona());
    }
    
    public void LlenarCombo(){
        Conexion c = new Conexion();
        c.EstableceConexion();
        ArrayList cargos = new ArrayList();
        this.cmbCargos.removeAllItems();
        cargos = c.GetListaCargos();
        Iterator iterador = cargos.iterator();
        while(iterador.hasNext()){
            ComboCargos CG = (ComboCargos) iterador.next();
            this.cmbCargos.addItem(CG.getCargos());
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void CargarTexto(){
        this.lblCargos.setText(prop.getProperty("lblCargos"));
        this.lblNombre.setText(prop.getProperty("lblNombre"));
        this.lblApellido.setText(prop.getProperty("lblApellido"));
        this.lblFechaNac.setText(prop.getProperty("lblFechaNac"));
        this.lblFechaReg.setText(prop.getProperty("lblFechaReg"));
        this.lblDUI.setText(prop.getProperty("lblDUI"));
        this.lblTelefono.setText(prop.getProperty("lblTelefono"));
        this.lblDir.setText(prop.getProperty("lblDir"));
        this.lblEstado.setText(prop.getProperty("lblEstado"));
        this.btnInsertar.setText(prop.getProperty("btnInsertar"));
        this.btnModificar.setText(prop.getProperty("btnModificar"));
        this.btnEliminar.setText(prop.getProperty("btnEliminar"));
        this.btnLimpiar.setText(prop.getProperty("btnLimpiar"));
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablePersonas = new javax.swing.JTable();
        lblCargos = new javax.swing.JLabel();
        cmbCargos = new javax.swing.JComboBox<>();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblFechaNac = new javax.swing.JLabel();
        jdcFechaNac = new com.toedter.calendar.JDateChooser();
        lblFechaReg = new javax.swing.JLabel();
        jdcFechaRegistro = new com.toedter.calendar.JDateChooser();
        lblDUI = new javax.swing.JLabel();
        txtDUI = new javax.swing.JTextField();
        lblDir = new javax.swing.JLabel();
        txtDir = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        rdbActivo = new javax.swing.JRadioButton();
        rdbDesactivo = new javax.swing.JRadioButton();
        btnInsertar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblTelefono = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Personas");
        setMaximumSize(new java.awt.Dimension(1920, 1080));

        TablePersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablePersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablePersonasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablePersonas);

        lblCargos.setText(".");

        cmbCargos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCargosItemStateChanged(evt);
            }
        });

        lblNombre.setText(".");

        lblApellido.setText(".");

        lblFechaNac.setText(".");

        lblFechaReg.setText(".");

        lblDUI.setText(".");

        txtDUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDUIActionPerformed(evt);
            }
        });

        lblDir.setText(".");

        lblEstado.setText(".");

        rdbActivo.setText("Activo");
        rdbActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbActivoActionPerformed(evt);
            }
        });

        rdbDesactivo.setText("Desactivo");
        rdbDesactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbDesactivoActionPerformed(evt);
            }
        });

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblTelefono.setText(".");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblEstado)
                            .addGap(33, 33, 33)
                            .addComponent(rdbActivo)
                            .addGap(38, 38, 38)
                            .addComponent(rdbDesactivo))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblCargos)
                            .addGap(27, 27, 27)
                            .addComponent(cmbCargos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblNombre)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNombre))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblApellido)
                            .addGap(18, 18, 18)
                            .addComponent(txtApellido))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblFechaReg)
                            .addGap(18, 18, 18)
                            .addComponent(jdcFechaRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblDUI)
                            .addGap(26, 26, 26)
                            .addComponent(txtDUI))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblFechaNac)
                            .addGap(12, 12, 12)
                            .addComponent(jdcFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblDir)
                            .addGap(18, 18, 18)
                            .addComponent(txtDir))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblTelefono)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInsertar)
                        .addGap(26, 26, 26)
                        .addComponent(btnModificar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lblCargos))
                            .addComponent(cmbCargos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApellido)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblFechaNac))
                            .addComponent(jdcFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblFechaReg))
                            .addComponent(jdcFechaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lblDUI))
                            .addComponent(txtDUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefono)
                            .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lblDir))
                            .addComponent(txtDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(lblEstado))
                            .addComponent(rdbActivo)
                            .addComponent(rdbDesactivo))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInsertar)
                            .addComponent(btnModificar)
                            .addComponent(btnEliminar)
                            .addComponent(btnLimpiar))
                        .addGap(24, 24, 24))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdbDesactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbDesactivoActionPerformed
        // TODO add your handling code here:
        if(this.rdbDesactivo.isSelected()){
            this.rdbActivo.setSelected(false);
            
        }
        else{
           this.rdbActivo.setSelected(false);
        
        }
    }//GEN-LAST:event_rdbDesactivoActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
        Personas pe = new Personas();
        int cargos = this.cmbCargos.getSelectedIndex()+1;
        String Nom = this.txtNombre.getText();
        String Ape = this.txtApellido.getText();
        String FechaNac = ((JTextField)this.jdcFechaNac.getDateEditor().getUiComponent()).getText();
        String FechaReg = ((JTextField)this.jdcFechaRegistro.getDateEditor().getUiComponent()).getText();
        int DUI = parseInt(this.txtDUI.getText());
        int Tel = parseInt(this.txtTel.getText());
        String Dir = this.txtDir.getText();
                        
        try{
            if(this.rdbActivo.isSelected()){
               String Activo = this.rdbActivo.getText(); 
               Activo = "A";
                if(pe.InsertarPersonas(cargos, Nom, Ape, FechaNac, FechaReg, DUI, Tel, Dir, Activo)>0){
                    JOptionPane.showMessageDialog(null, "datos ingresados");
                    this.TablePersonas.setModel(personas.CargarPersona());
                }
            }
            
            if(this.rdbDesactivo.isSelected()){
                String Desactivo = this.rdbDesactivo.getText();
                Desactivo = "D";
                if(pe.InsertarPersonas(cargos, Nom, Ape, FechaNac, FechaReg, DUI, Tel, Dir, Desactivo)>0){
                    JOptionPane.showMessageDialog(null, "datos ingresados");  
                    this.TablePersonas.setModel(personas.CargarPersona());
                }
            }
            
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "error: " + ex);
        }
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        
        ///Actualizar
        int cargos = this.cmbCargos.getSelectedIndex()+1;
        String Nom = this.txtNombre.getText();
        String Ape = this.txtApellido.getText();
        String FechaNac = ((JTextField)this.jdcFechaNac.getDateEditor().getUiComponent()).getText();
        String FechaReg = ((JTextField)this.jdcFechaRegistro.getDateEditor().getUiComponent()).getText();
        int DUI = parseInt(this.txtDUI.getText());
        int Tel = parseInt(this.txtTel.getText());
        String Dir = this.txtDir.getText();
        
         try{
            if(this.rdbActivo.isSelected()){
               String Activo = this.rdbActivo.getText(); 
               Activo = "A";
                if(this.personas.ModificiarPersonas(cargos, Nom, Ape, FechaNac, FechaReg, DUI, Tel, Dir, Activo)>0){
                    JOptionPane.showMessageDialog(null, "datos modificados");
                    this.TablePersonas.setModel(personas.CargarPersona());
                }
            }
            
            if(this.rdbDesactivo.isSelected()){
                String Desactivo = this.rdbDesactivo.getText();
                Desactivo = "D";
                if(this.personas.ModificiarPersonas(cargos, Nom, Ape, FechaNac, FechaReg, DUI, Tel, Dir, Desactivo)>0){
                    JOptionPane.showMessageDialog(null, "datos modificados");  
                    this.TablePersonas.setModel(personas.CargarPersona());
                }
            }
            
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "error: " + ex);
        }
        
        
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int d = parseInt(this.txtDUI.getText());
        int respuesta;
        respuesta = JOptionPane.showConfirmDialog(null, "¿Desea eliminar este registro?");
        
        if(respuesta == JOptionPane.YES_OPTION){
            try{
                if(this.personas.EliminarPersona(d)>0){
                    JOptionPane.showMessageDialog(null, "Datos eliminados");
                    this.CargarDatos();
                }
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, "Error");
            }
        }
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtDUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDUIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDUIActionPerformed

    private void cmbCargosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCargosItemStateChanged
        // TODO add your handling code here:
        Conexion c = new Conexion();
        c.EstableceConexion();
        ComboCargos cc = null;
        try{
            cc = (ComboCargos) this.cmbCargos.getSelectedItem();
            this.indiceCombo = cc.getCodCargos();
            JOptionPane.showMessageDialog(null, indiceCombo);
            
        }catch(ClassCastException ex){
            
        }
        
        
        
    }//GEN-LAST:event_cmbCargosItemStateChanged

    private void rdbActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbActivoActionPerformed
        // TODO add your handling code here:
        if(this.rdbActivo.isSelected()){
            this.rdbDesactivo.setSelected(false);
            
        }
        else{
           this.rdbDesactivo.setSelected(false);
        
        }
        
    }//GEN-LAST:event_rdbActivoActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        this.txtNombre.setText("");
        this.txtApellido.setText("");
        this.txtDUI.setText("");
        this.txtTel.setText("");
        ((JTextField)this.jdcFechaNac.getDateEditor().getUiComponent()).setText("");
        ((JTextField)this.jdcFechaRegistro.getDateEditor().getUiComponent()).setText("");
        this.rdbActivo.setSelected(false);
        this.rdbDesactivo.setSelected(false);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void TablePersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablePersonasMouseClicked
        // TODO add your handling code here:
        int seleccion = this.TablePersonas.getSelectedRow(); 
        
        String Cargos = this.TablePersonas.getValueAt(seleccion, 0).toString();
        switch(Cargos){
            case "Dentista":
                this.cmbCargos.setSelectedItem("Dentista");
            break;
            case "Secretario":
                this.cmbCargos.setSelectedItem("Secretario");
            break;
            case "Maxilofacial":
                this.cmbCargos.setSelectedItem("Maxilofacial");
            break;
            case "Cliente":
                this.cmbCargos.setSelectedItem("Cliente");
            break;
                
        }
        this.txtNombre.setText(this.TablePersonas.getValueAt(seleccion, 1).toString());
        this.txtApellido.setText(this.TablePersonas.getValueAt(seleccion, 2).toString());
        ((JTextField)this.jdcFechaRegistro.getDateEditor().getUiComponent()).setText(this.TablePersonas.getValueAt(seleccion, 3).toString());
        ((JTextField)this.jdcFechaNac.getDateEditor().getUiComponent()).setText(this.TablePersonas.getValueAt(seleccion, 4).toString());
        this.txtDUI.setText(this.TablePersonas.getValueAt(seleccion, 5).toString());
        this.txtTel.setText(this.TablePersonas.getValueAt(seleccion, 6).toString());
        this.txtDir.setText(this.TablePersonas.getValueAt(seleccion, 7).toString());
        String estado = this.TablePersonas.getValueAt(seleccion, 8).toString();
        if(estado.equals("A")){
            this.rdbActivo.setSelected(true);
            this.rdbDesactivo.setSelected(false);
        }else{
            this.rdbDesactivo.setSelected(true);
            this.rdbActivo.setSelected(false);
        }
        
        
        
    }//GEN-LAST:event_TablePersonasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablePersonas;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbCargos;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcFechaNac;
    private com.toedter.calendar.JDateChooser jdcFechaRegistro;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCargos;
    private javax.swing.JLabel lblDUI;
    private javax.swing.JLabel lblDir;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFechaNac;
    private javax.swing.JLabel lblFechaReg;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JRadioButton rdbActivo;
    private javax.swing.JRadioButton rdbDesactivo;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDUI;
    private javax.swing.JTextField txtDir;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
