/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ujmdprc4.clinicadental;
import Properties.RegistroProperties;
import Combos.ComboClienteCita;
import Combos.ComboDentistaFact;
import Clases.Factura;
import Combos.ComboProducto;
import Combos.ComboSecreFact;
import Conexion.Conexion;
import static Properties.RegistroProperties.prop;
import java.io.IOException;
import static java.lang.Float.parseFloat;
import static java.lang.Integer.parseInt;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author LENOVO
 */
public class InternalFrame_Factura extends javax.swing.JInternalFrame {
    Factura factura;
    RegistroProperties rp;
    /**
     * Creates new form InternalFrame_Factura
     */
    public InternalFrame_Factura() {
        try {
            rp = new RegistroProperties();
        } catch (IOException ex) {
            Logger.getLogger(InternalFrame_Factura.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        CargarTexto();
        this.setSize(900, 690);
        factura = new Factura();
        this.jdcFecha.setDateFormatString("yyyy-MM-dd");
        CargarTablaFactura();
        CargarDetalle();
        CargarClientes();
        CargarDentista();
        CargarSecretario();
        LlenarComboProducto();
    }
    
    public void CargarTablaFactura(){
        this.TablaFactura.setModel(factura.cargarFactura());
    }
    
    public void CargarDetalle(){
        this.tablaDetalle.setModel(factura.cargarDetalle());
    }
    
    public void CargarClientes(){
        Conexion c = new Conexion();
        c.EstableceConexion();
        ArrayList cli = new ArrayList();
        this.cmbCliente.removeAllItems();
        cli = c.GetListaClientesFact();
        Iterator iterador = cli.iterator();
        while(iterador.hasNext()){
            ComboClienteCita CCC = (ComboClienteCita) iterador.next();
            this.cmbCliente.addItem(CCC.getCliente());
        }
    }
    
    public void CargarDentista(){
        Conexion c = new Conexion();
        c.EstableceConexion();
        ArrayList d = new ArrayList();
        this.cmbDoctor.removeAllItems();
        d = c.GetListaDentistaFact();
        Iterator iterador = d.iterator();
        while(iterador.hasNext()){
            ComboDentistaFact CDF = (ComboDentistaFact) iterador.next();
            this.cmbDoctor.addItem(CDF.getDentista());
        }
    }
    
    public void CargarSecretario(){
        Conexion c = new Conexion();
        c.EstableceConexion();
        ArrayList sec = new ArrayList();
        this.cmbSecretaria.removeAllItems();
        sec = c.GetListaSecreFact();
        Iterator iterador = sec.iterator();
        while(iterador.hasNext()){
            ComboSecreFact CSF = (ComboSecreFact) iterador.next();
            this.cmbSecretaria.addItem(CSF.getSecretario());
        }
    }
    public void LlenarComboProducto(){
        Conexion c = new Conexion();
        c.EstableceConexion();
        ArrayList p = new ArrayList();
        this.cmbProducto.removeAllItems();
        p = c.GetListaProducto();
        Iterator iterador = p.iterator();
        while(iterador.hasNext()){
            ComboProducto CP = (ComboProducto) iterador.next();
            this.cmbProducto.addItem(CP.getProducto());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void CargarTexto(){
        this.lblCodFac.setText(prop.getProperty("lblCodFac"));
        this.lblNumFact.setText(prop.getProperty("lblNumFact"));
        this.lblFecha.setText(prop.getProperty("lblFecha"));
        this.lblSecFact.setText(prop.getProperty("lblSecFact"));
        this.lblDoctor.setText(prop.getProperty("lblDoctor"));
        this.lblClienteFact.setText(prop.getProperty("lblClienteFact"));
        this.btnGuardar.setText(prop.getProperty("btnGuardar"));
        this.btnEditar.setText(prop.getProperty("btnEditar"));
        this.btnEliminar.setText(prop.getProperty("btnEliminar"));
        this.btnLimpiar.setText(prop.getProperty("btnLimpiar"));
        this.lblCodDetFact.setText(prop.getProperty("lblCodDetFact"));
        this.lblNumDetFact.setText(prop.getProperty("lblNumDetFact"));
        this.lblProdDetFact.setText(prop.getProperty("lblProdDetFact"));
        this.lblCantDetFact.setText(prop.getProperty("lblCantDetFact"));
        this.lblPrecDetFact.setText(prop.getProperty("lblPrecDetFact"));
        this.btnGuardar1.setText(prop.getProperty("btnGuardar1"));
        this.btnEditar1.setText(prop.getProperty("btnEditar1"));
        this.btnEliminar1.setText(prop.getProperty("btnEliminar1"));
        this.btnLimpiar1.setText(prop.getProperty("btnLimpiar1"));
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCodFac = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblNumFact = new javax.swing.JLabel();
        txtNumFactura = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        lblSecFact = new javax.swing.JLabel();
        cmbSecretaria = new javax.swing.JComboBox<>();
        lblDoctor = new javax.swing.JLabel();
        cmbDoctor = new javax.swing.JComboBox<>();
        lblClienteFact = new javax.swing.JLabel();
        cmbCliente = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaFactura = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblCodDetFact = new javax.swing.JLabel();
        txtCodigoDeta = new javax.swing.JTextField();
        lblNumDetFact = new javax.swing.JLabel();
        txtNumFact = new javax.swing.JTextField();
        lblProdDetFact = new javax.swing.JLabel();
        cmbProducto = new javax.swing.JComboBox<>();
        lblCantDetFact = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        lblPrecDetFact = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDetalle = new javax.swing.JTable();
        btnGuardar1 = new javax.swing.JButton();
        btnEditar1 = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        btnLimpiar1 = new javax.swing.JButton();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Factura"));

        lblCodFac.setText(".");

        txtCodigo.setEnabled(false);

        lblNumFact.setText(".");

        lblFecha.setText(".");

        lblSecFact.setText(".");

        lblDoctor.setText(".");

        lblClienteFact.setText(".");

        TablaFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaFacturaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaFactura);

        btnGuardar.setText(".");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText(".");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEditar.setText(".");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnLimpiar.setText(".");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblFecha)
                            .addGap(18, 18, 18)
                            .addComponent(jdcFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblCodFac)
                            .addGap(18, 18, 18)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblNumFact)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNumFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblSecFact)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cmbSecretaria, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblDoctor)
                            .addGap(18, 18, 18)
                            .addComponent(cmbDoctor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblClienteFact)
                        .addGap(18, 18, 18)
                        .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodFac)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumFact)
                    .addComponent(txtNumFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFecha)
                    .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSecFact)
                    .addComponent(cmbSecretaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoctor)
                    .addComponent(cmbDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClienteFact)
                    .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar)
                    .addComponent(btnEditar)
                    .addComponent(btnLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle de Factura"));

        lblCodDetFact.setText(".");

        txtCodigoDeta.setEnabled(false);

        lblNumDetFact.setText(".");

        lblProdDetFact.setText(".");

        lblCantDetFact.setText(".");

        lblPrecDetFact.setText(".");

        tablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDetalleMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaDetalle);

        btnGuardar1.setText(".");
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });

        btnEditar1.setText(".");
        btnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar1ActionPerformed(evt);
            }
        });

        btnEliminar1.setText(".");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        btnLimpiar1.setText(".");
        btnLimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblProdDetFact)
                                    .addGap(18, 18, 18)
                                    .addComponent(cmbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(lblNumDetFact)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtNumFact))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(lblCodDetFact)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtCodigoDeta, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblCantDetFact)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtCantidad)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblPrecDetFact)
                                .addGap(18, 18, 18)
                                .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnGuardar1)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar1)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar1)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodDetFact)
                    .addComponent(txtCodigoDeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumDetFact)
                    .addComponent(txtNumFact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProdDetFact)
                    .addComponent(cmbProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantDetFact)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecDetFact)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar1)
                    .addComponent(btnEliminar1)
                    .addComponent(btnEditar1)
                    .addComponent(btnLimpiar1))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        this.txtCodigo.setText("");
        this.txtNumFactura.setText("");
        ((JTextField)this.jdcFecha.getDateEditor().getUiComponent()).setText("");
        
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int cod = parseInt(this.txtCodigo.getText());
        int numfac = parseInt(this.txtNumFactura.getText());
        String Fecha = ((JTextField)this.jdcFecha.getDateEditor().getUiComponent()).getText();
        String secre = this.cmbSecretaria.getSelectedItem().toString();
        String doctor = this.cmbDoctor.getSelectedItem().toString();
        String cliente = this.cmbCliente.getSelectedItem().toString();
        try {
            if(this.factura.Actualizar_Factura(cod, numfac, Fecha, secre, doctor, cliente)>0){
                JOptionPane.showMessageDialog(null, "datos modificados");
                this.CargarTablaFactura();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "error: " + ex);
            Logger.getLogger(InternalFrame_Factura.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar1ActionPerformed
        int cod = parseInt(this.txtCodigoDeta.getText());
        int numfac = parseInt(this.txtNumFact.getText());
        String prod = this.cmbProducto.getSelectedItem().toString();
        int cantidad = parseInt(this.txtCantidad.getText());
        float precio = parseFloat(this.txtPrecio.getText());
        try {
            if(this.factura.Actualizar_Detalle(cod, numfac, prod, cantidad, precio)>0){
                JOptionPane.showMessageDialog(null, "datos modificados");
                this.CargarDetalle();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "error: " + ex);
            Logger.getLogger(InternalFrame_Factura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditar1ActionPerformed

    private void btnLimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar1ActionPerformed
        // TODO add your handling code here:
        this.txtCodigoDeta.setText("");
        this.txtNumFact.setText("");
        this.txtCantidad.setText("");
        this.txtPrecio.setText("");
    }//GEN-LAST:event_btnLimpiar1ActionPerformed

    private void TablaFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaFacturaMouseClicked
        // TODO add your handling code here:
        int seleccion = this.TablaFactura.getSelectedRow();
        this.txtCodigo.setText(this.TablaFactura.getValueAt(seleccion, 0).toString());
        this.txtNumFactura.setText(this.TablaFactura.getValueAt(seleccion, 1).toString());
        ((JTextField)this.jdcFecha.getDateEditor().getUiComponent()).setText(this.TablaFactura.getValueAt(seleccion, 2).toString());
        
        
    }//GEN-LAST:event_TablaFacturaMouseClicked

    private void tablaDetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDetalleMouseClicked
        // TODO add your handling code here:
        int seleccion = this.tablaDetalle.getSelectedRow();
        this.txtCodigoDeta.setText(this.tablaDetalle.getValueAt(seleccion, 0).toString());
        this.txtNumFact.setText(this.tablaDetalle.getValueAt(seleccion, 1).toString());
        this.txtCantidad.setText(this.tablaDetalle.getValueAt(seleccion, 3).toString());
        this.txtPrecio.setText(this.tablaDetalle.getValueAt(seleccion, 4).toString());
        
    }//GEN-LAST:event_tablaDetalleMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
        int numfac = parseInt(this.txtNumFactura.getText());
        String Fecha = ((JTextField)this.jdcFecha.getDateEditor().getUiComponent()).getText();
        String secre = this.cmbSecretaria.getSelectedItem().toString();
        String doctor = this.cmbDoctor.getSelectedItem().toString();
        String cliente = this.cmbCliente.getSelectedItem().toString();
        try {
            if(this.factura.Insertar_Factura(numfac, Fecha, secre, doctor, cliente)>0){
                JOptionPane.showMessageDialog(null, "datos ingresados");
                this.CargarTablaFactura();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "error: " + ex);
            Logger.getLogger(InternalFrame_Factura.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int cod = parseInt(this.txtCodigo.getText());
        int respuesta;
        respuesta = JOptionPane.showConfirmDialog(null, "¿Desea eliminar este registro?");
        
        if(respuesta == JOptionPane.YES_OPTION){
            try{
                if(this.factura.Eliminar_Factura(cod)>0){
                    JOptionPane.showMessageDialog(null, "Datos eliminados");
                    this.CargarTablaFactura();
                }
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, "Error");
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        // TODO add your handling code here:
        int numfac = parseInt(this.txtNumFact.getText());
        String prod = this.cmbProducto.getSelectedItem().toString();
        int cantidad = parseInt(this.txtCantidad.getText());
        float precio = parseFloat(this.txtPrecio.getText());
        try {
            if(this.factura.Insertar_Detalle(numfac, prod, cantidad, precio)>0){
                JOptionPane.showMessageDialog(null, "datos ingresados");
                this.CargarDetalle();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "error: " + ex);
            Logger.getLogger(InternalFrame_Factura.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        // TODO add your handling code here:
        int cod = parseInt(this.txtCodigoDeta.getText());
        int respuesta;
        respuesta = JOptionPane.showConfirmDialog(null, "¿Desea eliminar este registro?");
        
        if(respuesta == JOptionPane.YES_OPTION){
            try{
                if(this.factura.Eliminar_detalle(cod)>0){
                    JOptionPane.showMessageDialog(null, "Datos eliminados");
                    this.CargarDetalle();
                }
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, "Error");
            }
        }
    }//GEN-LAST:event_btnEliminar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaFactura;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEditar1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiar1;
    private javax.swing.JComboBox<String> cmbCliente;
    private javax.swing.JComboBox<String> cmbDoctor;
    private javax.swing.JComboBox<String> cmbProducto;
    private javax.swing.JComboBox<String> cmbSecretaria;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private javax.swing.JLabel lblCantDetFact;
    private javax.swing.JLabel lblClienteFact;
    private javax.swing.JLabel lblCodDetFact;
    private javax.swing.JLabel lblCodFac;
    private javax.swing.JLabel lblDoctor;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNumDetFact;
    private javax.swing.JLabel lblNumFact;
    private javax.swing.JLabel lblPrecDetFact;
    private javax.swing.JLabel lblProdDetFact;
    private javax.swing.JLabel lblSecFact;
    private javax.swing.JTable tablaDetalle;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoDeta;
    private javax.swing.JTextField txtNumFact;
    private javax.swing.JTextField txtNumFactura;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
