/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ujmdprc4.clinicadental;
import Properties.RegistroProperties;
import Clases.Factura;
import static Properties.RegistroProperties.prop;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class InternalFrame_Ticket extends javax.swing.JInternalFrame {
Factura factura;
RegistroProperties rp;
    /**
     * Creates new form InternalFrame_Ticket
     */
    public InternalFrame_Ticket() {
    try {
        rp = new RegistroProperties();
    } catch (IOException ex) {
        Logger.getLogger(InternalFrame_Ticket.class.getName()).log(Level.SEVERE, null, ex);
    }
        initComponents();
        CargarTexto();
        this.setSize(957, 600);
        factura = new Factura();
        CargarTablaTicket();
    }
    
    public void CargarTablaTicket(){
        this.tablaTicket.setModel(this.factura.cargarTicket());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void CargarTexto(){
        this.btnGenerarTicket.setText(prop.getProperty("btnGenerarTicket"));
        this.lblTicket.setText(prop.getProperty("lblTicket"));
        this.lblNum.setText(prop.getProperty("lblNum"));
        this.lblFECHA.setText(prop.getProperty("lblFECHA"));
        this.lblSECRE.setText(prop.getProperty("lblSECRE"));
        this.lblDOC.setText(prop.getProperty("lblDOC"));
        this.lblCLIENTE.setText(prop.getProperty("lblCLIENTE"));
        this.lblPROD.setText(prop.getProperty("lblPROD"));
        this.lblCANT.setText(prop.getProperty("lblCANT"));
        this.lblPRECIO.setText(prop.getProperty("lblPRECIO"));
        this.lblTOTAL.setText(prop.getProperty("lblTOTAL"));
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTicket = new javax.swing.JTable();
        lblTicket = new javax.swing.JLabel();
        lblNum = new javax.swing.JLabel();
        lblNumFactura = new javax.swing.JLabel();
        lblFECHA = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblSECRE = new javax.swing.JLabel();
        lblSecretaria = new javax.swing.JLabel();
        lblDOC = new javax.swing.JLabel();
        lblDoctor = new javax.swing.JLabel();
        lblCLIENTE = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblPROD = new javax.swing.JLabel();
        lblProducto = new javax.swing.JLabel();
        lblCANT = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblPRECIO = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblTOTAL = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnGenerarTicket = new javax.swing.JButton();

        setBorder(null);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tablaTicket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaTicketMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaTicket);

        lblTicket.setText(".");

        lblNum.setText(".");

        lblNumFactura.setForeground(new java.awt.Color(204, 0, 0));

        lblFECHA.setText(".");

        lblFecha.setForeground(new java.awt.Color(0, 0, 204));

        lblSECRE.setText(".");

        lblSecretaria.setForeground(new java.awt.Color(0, 0, 204));

        lblDOC.setText(".");

        lblDoctor.setForeground(new java.awt.Color(0, 0, 204));

        lblCLIENTE.setText(".");

        lblCliente.setForeground(new java.awt.Color(0, 0, 204));

        lblPROD.setText(".");

        lblProducto.setForeground(new java.awt.Color(0, 0, 204));

        lblCANT.setText(".");

        lblCantidad.setForeground(new java.awt.Color(0, 0, 204));

        lblPRECIO.setText(".");

        lblPrecio.setForeground(new java.awt.Color(0, 0, 204));

        lblTOTAL.setText(".");

        lblTotal.setForeground(new java.awt.Color(0, 0, 204));

        btnGenerarTicket.setText(".");
        btnGenerarTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarTicketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCLIENTE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCliente)
                                .addGap(833, 833, 833))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDOC)
                                .addGap(18, 18, 18)
                                .addComponent(lblDoctor))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSECRE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSecretaria))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFECHA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblFecha))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNum)
                                .addGap(18, 18, 18)
                                .addComponent(lblNumFactura))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 927, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPROD)
                                .addGap(18, 18, 18)
                                .addComponent(lblProducto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCANT)
                                .addGap(18, 18, 18)
                                .addComponent(lblCantidad))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPRECIO)
                                .addGap(18, 18, 18)
                                .addComponent(lblPrecio))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTOTAL)
                                .addGap(18, 18, 18)
                                .addComponent(lblTotal)))
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTicket)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGenerarTicket)
                        .addGap(73, 73, 73))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTicket)
                    .addComponent(btnGenerarTicket))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNum)
                    .addComponent(lblNumFactura))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFECHA)
                    .addComponent(lblFecha))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSECRE)
                    .addComponent(lblSecretaria))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDOC)
                    .addComponent(lblDoctor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCLIENTE)
                    .addComponent(lblCliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPROD)
                    .addComponent(lblProducto))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCANT)
                    .addComponent(lblCantidad))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPRECIO)
                    .addComponent(lblPrecio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTOTAL)
                    .addComponent(lblTotal))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaTicketMouseClicked
        // TODO add your handling code here:
        int seleccion = this.tablaTicket.getSelectedRow();
        this.lblNumFactura.setText(this.tablaTicket.getValueAt(seleccion, 0).toString());
        this.lblFecha.setText(this.tablaTicket.getValueAt(seleccion, 1).toString());
        this.lblSecretaria.setText(this.tablaTicket.getValueAt(seleccion, 2).toString());
        this.lblDoctor.setText(this.tablaTicket.getValueAt(seleccion, 3).toString());
        this.lblCliente.setText(this.tablaTicket.getValueAt(seleccion, 4).toString());
        this.lblProducto.setText(this.tablaTicket.getValueAt(seleccion, 5).toString());
        this.lblCantidad.setText(this.tablaTicket.getValueAt(seleccion, 6).toString());
        this.lblPrecio.setText(this.tablaTicket.getValueAt(seleccion, 7).toString());
        this.lblTotal.setText(this.tablaTicket.getValueAt(seleccion, 8).toString());
    }//GEN-LAST:event_tablaTicketMouseClicked

    private void btnGenerarTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarTicketActionPerformed
        // TODO add your handling code here:
        
        FileWriter archivo = null;
        PrintWriter pw;
        try{
            archivo = new FileWriter("Ticket.txt",true);
            pw = new PrintWriter(archivo);
            pw.println("Factura Maxident");
            pw.println(this.lblNum.getText()+" "+this.lblNumFactura.getText());
            pw.println(this.lblFECHA.getText()+" "+this.lblFecha.getText());
            pw.println(this.lblSECRE.getText()+" "+this.lblSecretaria.getText());
            pw.println(this.lblDOC.getText()+" "+this.lblDoctor.getText());
            pw.println(this.lblCLIENTE.getText()+" "+this.lblCliente.getText());
            pw.println(this.lblPROD.getText()+" "+this.lblProducto.getText());
            pw.println(this.lblCANT.getText()+" "+this.lblCantidad.getText());
            pw.println(this.lblPRECIO.getText()+" "+this.lblPrecio.getText());
            pw.println(this.lblTOTAL.getText()+" "+this.lblTotal.getText());
            pw.println("-------------------------------------------");
        }catch(IOException ex){
            
        }finally {
            try {
                archivo.close();
                JOptionPane.showMessageDialog(null, "Ticket generado");
            } catch (IOException ex) {
                Logger.getLogger(InternalFrame_Ticket.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnGenerarTicketActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarTicket;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCANT;
    private javax.swing.JLabel lblCLIENTE;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblDOC;
    private javax.swing.JLabel lblDoctor;
    private javax.swing.JLabel lblFECHA;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNum;
    private javax.swing.JLabel lblNumFactura;
    private javax.swing.JLabel lblPRECIO;
    private javax.swing.JLabel lblPROD;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblSECRE;
    private javax.swing.JLabel lblSecretaria;
    private javax.swing.JLabel lblTOTAL;
    private javax.swing.JLabel lblTicket;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tablaTicket;
    // End of variables declaration//GEN-END:variables
}
