/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package ujmdprc4.clinicadental;

import Clases.ClaseIngreso;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class MDI_Principal extends javax.swing.JFrame {
    ClaseIngreso ingreso;

    /**
     * Creates new form MDI_Principal
     */
    public MDI_Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.escritorio.setSize(1920, 1080);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        escritorio = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        PersonasMenu = new javax.swing.JMenu();
        MenuItemPersonas = new javax.swing.JMenuItem();
        MenuItemUsuarios = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        CitaMenu = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        FacturaMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        desktop.add(escritorio);
        escritorio.setBounds(0, 0, 400, 280);

        PersonasMenu.setMnemonic('f');
        PersonasMenu.setText("Personas");
        PersonasMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PersonasMenuMouseClicked(evt);
            }
        });

        MenuItemPersonas.setText("Personas");
        MenuItemPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemPersonasActionPerformed(evt);
            }
        });
        PersonasMenu.add(MenuItemPersonas);

        MenuItemUsuarios.setText("Usuarios");
        MenuItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemUsuariosActionPerformed(evt);
            }
        });
        PersonasMenu.add(MenuItemUsuarios);

        menuBar.add(PersonasMenu);

        jMenu2.setText("Sucursales");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        menuBar.add(jMenu2);

        CitaMenu.setMnemonic('h');
        CitaMenu.setText("Citas");
        CitaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CitaMenuMouseClicked(evt);
            }
        });
        CitaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CitaMenuActionPerformed(evt);
            }
        });
        menuBar.add(CitaMenu);

        jMenu1.setText("Productos");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        menuBar.add(jMenu1);

        FacturaMenu.setText("Ticket");
        FacturaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FacturaMenuMouseClicked(evt);
            }
        });
        FacturaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FacturaMenuActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Factura");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        FacturaMenu.add(jMenuItem1);

        jMenuItem2.setText("Imprimir Ticket");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        FacturaMenu.add(jMenuItem2);

        menuBar.add(FacturaMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PersonasMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PersonasMenuMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PersonasMenuMouseClicked

    private void MenuItemPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemPersonasActionPerformed
        // TODO add your handling code here:
        InternalFrame_Personas personas = null;
        try {
            personas = new InternalFrame_Personas();
            escritorio.add(personas);
        personas.toFront();
        personas.show();
        } catch (SQLException | NullPointerException ex) {
            
        }
        
    }//GEN-LAST:event_MenuItemPersonasActionPerformed

    private void MenuItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemUsuariosActionPerformed
        // TODO add your handling code here:
        InternalFrame_Usuarios usuarios = null;
        try{
            usuarios = new InternalFrame_Usuarios();
            
        }catch(NullPointerException ex){
            Logger.getLogger(MDI_Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.escritorio.add(usuarios);
        usuarios.toFront();
        usuarios.show();
    }//GEN-LAST:event_MenuItemUsuariosActionPerformed

    private void CitaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CitaMenuActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_CitaMenuActionPerformed

    private void CitaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CitaMenuMouseClicked
        // TODO add your handling code here:
        InternalFrame_Citas citas = null;
        try{
            citas = new InternalFrame_Citas();
        this.escritorio.add(citas);
        citas.toFront();
        citas.show();
        }catch(NullPointerException ex){
            
        }
        
    }//GEN-LAST:event_CitaMenuMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        InternalFrame_Sucursal sucursal = null;
        try{
            sucursal = new InternalFrame_Sucursal();
        this.escritorio.add(sucursal);
        sucursal.toFront();
        sucursal.show();
        }catch(NullPointerException ex){
            
        }
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        InternalFrame_Productos producto = null;
        try{
            producto = new InternalFrame_Productos();
        this.escritorio.add(producto);
        producto.toFront();
        producto.show();
        }catch(NullPointerException ex){
            
        }
    }//GEN-LAST:event_jMenu1MouseClicked

    private void FacturaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FacturaMenuMouseClicked
        // TODO add your handling code here:
        
                
    }//GEN-LAST:event_FacturaMenuMouseClicked

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         InternalFrame_Factura factura = null;
        try{
            factura = new InternalFrame_Factura();
        this.escritorio.add(factura);
        factura.toFront();
        factura.show();
        }catch(NullPointerException ex){
            
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void FacturaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FacturaMenuActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_FacturaMenuActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         InternalFrame_Ticket ticket = null;
        try{
            ticket = new InternalFrame_Ticket();
        this.escritorio.add(ticket);
        ticket.toFront();
        ticket.show();
        }catch(NullPointerException ex){
            
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDI_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDI_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu CitaMenu;
    private javax.swing.JMenu FacturaMenu;
    private javax.swing.JMenuItem MenuItemPersonas;
    private javax.swing.JMenuItem MenuItemUsuarios;
    private javax.swing.JMenu PersonasMenu;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JPanel escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
